#!/usr/bin/env Rscript
# csv_to_bib.R — one-time migration: publications CSV → publications.bib
#
# Usage: Rscript scripts/csv_to_bib.R path/to/publications.csv
#
# Expected CSV columns (flexible — script will print unmapped columns):
#   authors, year, title, venue, type, doi, url, keywords, abstract, featured, pdf

suppressPackageStartupMessages({
  library(readr)
  library(dplyr)
  library(stringr)
  library(bibtex)   # may need: install.packages("bibtex")
})

args <- commandArgs(trailingOnly = TRUE)
if (length(args) == 0) stop("Usage: Rscript scripts/csv_to_bib.R <path_to_csv>")

csv_path <- args[1]
out_path <- "publications/publications.bib"

csv <- read_csv(csv_path, show_col_types = FALSE)
message("Loaded ", nrow(csv), " rows from ", csv_path)
message("Columns found: ", paste(names(csv), collapse = ", "))

# ── Column mapping (adjust if your CSV uses different names) ────────────────
COL <- list(
  authors  = "authors",
  year     = "year",
  title    = "title",
  venue    = "venue",
  type     = "type",       # article | book | chapter | other
  doi      = "doi",
  url      = "url",
  keywords = "keywords",   # semicolon-separated
  abstract = "abstract",
  featured = "featured",   # TRUE/FALSE
  pdf      = "pdf"
)

# ── Citation key generator ───────────────────────────────────────────────────
make_key <- function(authors, year, title) {
  last <- str_extract(authors, "^[^,;]+") |>
    str_remove_all("[^A-Za-z]") |>
    str_to_lower()
  word <- str_extract_all(title, "\\b[A-Z][a-z]{3,}\\b")[[1]][1] |>
    str_to_lower()
  word <- if (is.na(word)) "x" else word
  paste0(last, year, word)
}

# ── Type → BibTeX entry type ─────────────────────────────────────────────────
bib_type <- function(type) {
  type <- str_to_lower(type)
  case_when(
    str_detect(type, "article|journal") ~ "article",
    str_detect(type, "book$")           ~ "book",
    str_detect(type, "chapter|incoll")  ~ "incollection",
    str_detect(type, "proceed|conf")    ~ "inproceedings",
    TRUE                                 ~ "misc"
  )
}

# ── Build BibTeX text ────────────────────────────────────────────────────────
errors <- character()
lines  <- c(
  "% Generated by scripts/csv_to_bib.R",
  paste0("% Source: ", csv_path),
  paste0("% Date:   ", Sys.Date()),
  ""
)

for (i in seq_len(nrow(csv))) {
  row <- csv[i, ]

  # Required fields check
  missing <- c()
  for (f in c("authors", "year", "title")) {
    v <- row[[COL[[f]]]]
    if (is.na(v) || str_trim(v) == "") missing <- c(missing, f)
  }
  if (length(missing)) {
    errors <- c(errors, sprintf("Row %d: missing required fields: %s", i, paste(missing, collapse = ", ")))
    next
  }

  authors  <- row[[COL$authors]]
  year     <- row[[COL$year]]
  title    <- row[[COL$title]]
  venue    <- if (!is.null(COL$venue)  && !is.na(row[[COL$venue]]))  row[[COL$venue]]  else ""
  type     <- if (!is.null(COL$type)   && !is.na(row[[COL$type]]))   row[[COL$type]]   else "article"
  doi      <- if (!is.null(COL$doi)    && !is.na(row[[COL$doi]]))    row[[COL$doi]]    else ""
  url      <- if (!is.null(COL$url)    && !is.na(row[[COL$url]]))    row[[COL$url]]    else ""
  keywords <- if (!is.null(COL$keywords) && !is.na(row[[COL$keywords]])) row[[COL$keywords]] else ""
  abstract <- if (!is.null(COL$abstract) && !is.na(row[[COL$abstract]])) row[[COL$abstract]] else ""
  featured <- if (!is.null(COL$featured) && isTRUE(as.logical(row[[COL$featured]]))) "true" else ""
  pdf      <- if (!is.null(COL$pdf)    && !is.na(row[[COL$pdf]]))    row[[COL$pdf]]    else ""

  btype <- bib_type(type)
  key   <- make_key(authors, year, title)

  venue_field <- switch(btype,
    article        = paste0("  journal   = {", venue, "},"),
    book           = paste0("  publisher = {", venue, "},"),
    incollection   = paste0("  booktitle = {", venue, "},"),
    inproceedings  = paste0("  booktitle = {", venue, "},"),
    paste0("  howpublished = {", venue, "},")
  )

  entry <- c(
    paste0("@", btype, "{", key, ","),
    paste0("  author    = {", authors, "},"),
    paste0("  title     = {", title, "},"),
    paste0("  year      = {", year, "},"),
    venue_field,
    if (nchar(doi))      paste0("  doi       = {", doi, "},"),
    if (nchar(url))      paste0("  url       = {", url, "},"),
    if (nchar(keywords)) paste0("  keywords  = {", keywords, "},"),
    if (nchar(abstract)) paste0("  abstract  = {", abstract, "},"),
    if (nchar(featured)) paste0("  featured  = {", featured, "},"),
    if (nchar(pdf))      paste0("  pdf       = {", pdf, "},"),
    "}",
    ""
  )
  entry <- entry[!sapply(entry, is.null)]
  lines <- c(lines, entry)
}

writeLines(lines, out_path)
message("Wrote ", out_path)

if (length(errors)) {
  message("\n── Rows with errors (fix manually) ──────────────")
  message(paste(errors, collapse = "\n"))
} else {
  message("All rows processed without errors.")
}
