#!/usr/bin/env Rscript
# gen_bib.R — convert G:/My Drive/CV/publications.csv → publications/publications.bib
# Uses only base R; no package dependencies.

# Resolve project root relative to this script's location so it works from any wd
script_path <- normalizePath(
  sub("--file=", "", grep("--file=", commandArgs(trailingOnly = FALSE), value = TRUE)[1]),
  mustWork = FALSE
)
proj_root <- normalizePath(file.path(dirname(script_path), ".."), mustWork = FALSE)
setwd(proj_root)

csv_path <- "G:/My Drive/CV/publications.csv"
out_path <- "publications/publications.bib"

dat <- read.csv(csv_path, stringsAsFactors = FALSE, na.strings = c("", "NA"))

# ── Helpers ──────────────────────────────────────────────────────────────────

# Parse "First Last" → "Last, First"
flip_name <- function(name) {
  name <- trimws(gsub("\\(equal authors\\)", "", name))
  parts <- strsplit(name, "\\s+")[[1]]
  if (length(parts) < 2) return(name)
  paste0(parts[length(parts)], ", ", paste(parts[-length(parts)], collapse = " "))
}

# Parse author string → BibTeX "Last, First and Last, First ..."
bib_authors <- function(s) {
  if (is.na(s) || !nchar(trimws(s))) return("")
  # split on ", and " | " and " | "," (but not within a name part)
  s <- trimws(s)
  # Replace ", and " and " and " with a separator we control
  s2 <- gsub(",\\s+and\\s+", " && ", s)
  s2 <- gsub("\\s+and\\s+", " && ", s2)
  # remaining commas separate authors in some styles
  s2 <- gsub(",\\s+", " && ", s2)
  parts <- trimws(strsplit(s2, " && ")[[1]])
  parts <- parts[nchar(parts) > 0]
  paste(sapply(parts, flip_name), collapse = " and ")
}

# Citation key: [firstAuthorLastName][year][firstSignificantWord]
make_key <- function(authors, year, title) {
  # First author last name
  s <- trimws(gsub("\\(equal authors\\)", "", authors))
  first_author <- trimws(strsplit(s, ",\\s+and\\s+|\\s+and\\s+|,\\s+")[[1]][1])
  name_parts <- strsplit(trimws(first_author), "\\s+")[[1]]
  last <- tolower(name_parts[length(name_parts)])
  last <- gsub("[^a-z]", "", last)
  # First significant word (>3 chars, not stop words)
  stop_words <- c("the", "a", "an", "of", "in", "on", "at", "to", "for",
                  "and", "or", "but", "with", "from", "by", "is", "are",
                  "does", "its", "their", "this", "that", "how", "why",
                  "when", "what", "who", "did")
  words <- strsplit(gsub("[^A-Za-z ]", " ", title), "\\s+")[[1]]
  sig <- Filter(function(w) nchar(w) > 3 && !tolower(w) %in% stop_words, words)
  word <- if (length(sig) > 0) tolower(sig[1]) else "x"
  paste0(last, year, word)
}

# Parse "131(1):200-237" → list(volume, number, pages)
parse_vip <- function(s) {
  if (is.na(s) || !nchar(trimws(s))) return(list(volume="", number="", pages=""))
  s <- trimws(s)
  vol <- ""; num <- ""; pgs <- ""
  # e.g. 131(1):200-237  or  50:431-453  or  117-134  or  65(1):12-34
  m <- regmatches(s, regexec("^(\\d+)\\((\\d+)\\):(\\S+)$", s))[[1]]
  if (length(m) == 4) { vol <- m[2]; num <- m[3]; pgs <- m[4]; return(list(volume=vol,number=num,pages=pgs)) }
  m2 <- regmatches(s, regexec("^(\\d+):(\\S+)$", s))[[1]]
  if (length(m2) == 3) { vol <- m2[2]; pgs <- m2[3]; return(list(volume=vol,number=num,pages=pgs)) }
  # just pages
  list(volume=vol, number=num, pages=s)
}

# BibTeX entry type
bib_type <- function(type) {
  type <- tolower(trimws(type))
  if (type == "article")  return("article")
  if (type == "book")     return("book")
  if (type == "chapter")  return("incollection")
  if (type == "working")  return("unpublished")
  "misc"
}

# BibTeX field line — note trailing comma required by BibTeX syntax
field <- function(name, value) {
  if (is.na(value) || !nchar(trimws(value))) return(NULL)
  sprintf("  %-12s= {%s},", name, trimws(value))
}

# ── Build .bib ────────────────────────────────────────────────────────────────

lines <- c(
  "% publications.bib — generated by scripts/gen_bib.R",
  paste0("% Source: ", csv_path),
  paste0("% Date:   ", Sys.Date()),
  ""
)

used_keys <- character()

for (i in seq_len(nrow(dat))) {
  r <- dat[i, ]

  btype  <- bib_type(r$type)
  year   <- as.character(r$year)
  title  <- r$title
  venue  <- if (!is.na(r$venue)) r$venue else ""
  auth   <- bib_authors(r$authors)
  vip    <- parse_vip(r$volume_issue_pages)
  doi    <- if (!is.na(r$doi))     r$doi     else ""
  url    <- if (!is.na(r$pdf_url)) r$pdf_url else ""
  kw     <- if (!is.na(r$keywords)) r$keywords else ""
  abstr  <- if (!is.na(r$abstract)) r$abstract else ""
  feat   <- if (!is.na(r$featured) && tolower(trimws(r$featured)) == "y") "true" else ""

  # Unique citation key
  base_key <- make_key(r$authors, year, title)
  key <- base_key
  suffix <- letters
  si <- 1
  while (key %in% used_keys) { key <- paste0(base_key, suffix[si]); si <- si + 1 }
  used_keys <- c(used_keys, key)

  # Venue field name by type
  venue_name <- switch(btype,
    article      = "journal",
    book         = "publisher",
    incollection = "booktitle",
    unpublished  = "note",
    "howpublished"
  )

  venue_val <- venue
  if (btype == "unpublished") {
    venue_val <- if (nchar(venue)) paste0("Working paper, ", venue) else "Working paper"
  }

  entry_lines <- c(
    paste0("@", btype, "{", key, ","),
    field("author",   auth),
    field("title",    title),
    field("year",     year),
    field(venue_name, venue_val),
    if (nchar(vip$volume)) field("volume",  vip$volume),
    if (nchar(vip$number)) field("number",  vip$number),
    if (nchar(vip$pages))  field("pages",   vip$pages),
    if (nchar(doi))        field("doi",     doi),
    if (nchar(url))        field("url",     url),
    if (nchar(kw))         field("keywords", kw),
    if (nchar(abstr))      field("abstract", abstr),
    if (nchar(feat))       field("featured", feat),
    "}",
    ""
  )
  entry_lines <- Filter(Negate(is.null), entry_lines)
  lines <- c(lines, entry_lines)
}

writeLines(lines, out_path, useBytes = FALSE)
cat(sprintf("Wrote %s  (%d entries)\n", out_path, nrow(dat)))
