// D3 force-directed publications network
// Data loaded from network.json (generated by scripts/bib_to_network.R)

(function () {
  const TYPE_COLOR = {
    article: "#4e79a7",
    book:    "#f28e2b",
    chapter: "#59a14f",
    other:   "#b07aa1",
  };

  const container = document.getElementById("network-container");
  if (!container) return;

  const width  = container.clientWidth  || 500;
  const height = Math.round(width * 0.75);

  const svg = d3.select("#pub-network")
    .attr("width",  width)
    .attr("height", height)
    .attr("viewBox", [0, 0, width, height]);

  // Tooltip
  const tooltip = d3.select("body").append("div")
    .style("position", "absolute")
    .style("background", "#fff")
    .style("border", "1px solid #ccc")
    .style("border-radius", "4px")
    .style("padding", "6px 10px")
    .style("font-size", "0.8rem")
    .style("pointer-events", "none")
    .style("opacity", 0);

  // Detail panel (right side — injected on click)
  const detailPanel = d3.select(".filter-panel").insert("div", ":first-child")
    .attr("id", "node-detail")
    .style("display", "none")
    .style("margin-bottom", "1rem")
    .style("padding", "0.75rem")
    .style("border", "1px solid #ccc")
    .style("border-radius", "4px")
    .style("font-size", "0.85rem");

  fetch("network.json")
    .then(r => r.json())
    .then(data => drawGraph(data))
    .catch(() => {
      container.innerHTML =
        '<p style="padding:1rem;color:#888;font-size:0.85rem">Network data not yet generated. Run <code>quarto render</code> after populating publications.bib.</p>';
    });

  function drawGraph({ nodes, edges }) {
    // Store for dimming updates
    window._networkNodes = nodes;
    window._networkEdges = edges;

    const simulation = d3.forceSimulation(nodes)
      .force("link",   d3.forceLink(edges).id(d => d.id).distance(60).strength(0.4))
      .force("charge", d3.forceManyBody().strength(-120))
      .force("center", d3.forceCenter(width / 2, height / 2))
      .force("collide", d3.forceCollide(10));

    const link = svg.append("g").selectAll("line")
      .data(edges).join("line")
      .attr("stroke", "#ccc")
      .attr("stroke-width", d => Math.sqrt(d.weight));

    const node = svg.append("g").selectAll("circle")
      .data(nodes).join("circle")
      .attr("r", 7)
      .attr("fill", d => TYPE_COLOR[d.type] || TYPE_COLOR.other)
      .attr("stroke", "#fff")
      .attr("stroke-width", 1.5)
      .attr("cursor", "pointer")
      .call(d3.drag()
        .on("start", (event, d) => { if (!event.active) simulation.alphaTarget(0.3).restart(); d.fx = d.x; d.fy = d.y; })
        .on("drag",  (event, d) => { d.fx = event.x; d.fy = event.y; })
        .on("end",   (event, d) => { if (!event.active) simulation.alphaTarget(0); d.fx = null; d.fy = null; }));

    node
      .on("mouseover", (event, d) => {
        tooltip.style("opacity", 1).html(d.title);
      })
      .on("mousemove", event => {
        tooltip.style("left", (event.pageX + 12) + "px").style("top", (event.pageY - 20) + "px");
      })
      .on("mouseout", () => tooltip.style("opacity", 0))
      .on("click", (event, d) => showDetail(d));

    simulation.on("tick", () => {
      link
        .attr("x1", d => d.source.x).attr("y1", d => d.source.y)
        .attr("x2", d => d.target.x).attr("y2", d => d.target.y);
      node
        .attr("cx", d => Math.max(8, Math.min(width  - 8, d.x)))
        .attr("cy", d => Math.max(8, Math.min(height - 8, d.y)));
    });

    // Expose handles for dimming from filter.js
    window._networkSvgNodes = node;
    window._networkSvgLinks = link;
  }

  function showDetail(d) {
    const doi = d.doi ? `<a href="https://doi.org/${d.doi}" target="_blank">DOI</a>` : "";
    const url = d.url ? `<a href="${d.url}" target="_blank">Link</a>` : "";
    const links = [doi, url].filter(Boolean).join(" &nbsp; ");
    detailPanel
      .style("display", "block")
      .html(`
        <strong>${d.title}</strong><br>
        <span style="color:#666">${d.year} · ${d.outlet || ""}</span><br>
        ${d.abstract ? `<p style="margin:0.5rem 0">${d.abstract}</p>` : ""}
        ${links}
        <br><small style="color:#aaa">${(d.keywords || []).join(", ")}</small>
      `);
  }
})();
