// D3 force-directed publications network
// Data loaded from network.json (generated by scripts/bib_to_network.R)

(function () {
  // Palette drawn from the hero image (Korean minhwa tiger):
  // teal-blue ground, gold tiger, terracotta flame, sage clouds.
  const TYPE_COLOR = {
    article: "#2f6078",  // deep teal-blue
    book:    "#dca233",  // gold
    chapter: "#c0492e",  // terracotta red
    other:   "#6f8b7e",  // muted sage
  };

  const container = document.getElementById("network-container");
  if (!container) return;

  const width  = container.clientWidth  || 500;
  const height = Math.min(Math.round(width * 0.55), 620);

  const svg = d3.select("#pub-network")
    .attr("width",  width)
    .attr("height", height)
    .attr("viewBox", [0, 0, width, height]);

  // Tooltip
  const tooltip = d3.select("body").append("div")
    .style("position", "absolute")
    .style("background", "#fff")
    .style("border", "1px solid #ccc")
    .style("border-radius", "4px")
    .style("padding", "6px 10px")
    .style("font-size", "0.8rem")
    .style("pointer-events", "none")
    .style("opacity", 0);

  fetch("publications/network.json")
    .then(r => r.json())
    .then(data => drawGraph(data))
    .catch(() => {
      container.innerHTML =
        '<p style="padding:1rem;color:#888;font-size:0.85rem">Network data not yet generated. Run <code>quarto render</code> after populating publications.bib.</p>';
    });

  function drawGraph({ nodes, edges }) {
    // Store for dimming updates
    window._networkNodes = nodes;
    window._networkEdges = edges;

    // Node radius from citation count (sqrt scale so area ~ citations)
    const maxCites = d3.max(nodes, d => d.citations || 0) || 1;
    const rScale = d3.scaleSqrt().domain([0, maxCites]).range([5, 18]);
    const nodeRadius = d => rScale(d.citations || 0);

    const simulation = d3.forceSimulation(nodes)
      .force("link",   d3.forceLink(edges).id(d => d.id).distance(60).strength(0.4))
      .force("charge", d3.forceManyBody().strength(-120))
      .force("center", d3.forceCenter(width / 2, height / 2))
      .force("collide", d3.forceCollide(d => nodeRadius(d) + 2));

    const link = svg.append("g").selectAll("line")
      .data(edges).join("line")
      .attr("stroke", "#ccc")
      .attr("stroke-width", d => Math.sqrt(d.weight));

    const node = svg.append("g").selectAll("circle")
      .data(nodes).join("circle")
      .attr("r", nodeRadius)
      .attr("fill", d => TYPE_COLOR[d.type] || TYPE_COLOR.other)
      .attr("stroke", "#fff")
      .attr("stroke-width", 1.5)
      .attr("cursor", "pointer")
      .call(d3.drag()
        .on("start", (event, d) => { if (!event.active) simulation.alphaTarget(0.3).restart(); d.fx = d.x; d.fy = d.y; })
        .on("drag",  (event, d) => { d.fx = event.x; d.fy = event.y; })
        .on("end",   (event, d) => { if (!event.active) simulation.alphaTarget(0); d.fx = null; d.fy = null; }));

    node
      .on("mouseover", (event, d) => {
        tooltip.style("opacity", 1).html(d.title);
      })
      .on("mousemove", event => {
        tooltip.style("left", (event.pageX + 12) + "px").style("top", (event.pageY - 20) + "px");
      })
      .on("mouseout", () => tooltip.style("opacity", 0))
      .on("click", (event, d) => {
        if (typeof window.showPubById === "function") window.showPubById(d.id);
      });

    simulation.on("tick", () => {
      link
        .attr("x1", d => d.source.x).attr("y1", d => d.source.y)
        .attr("x2", d => d.target.x).attr("y2", d => d.target.y);
      node
        .attr("cx", d => { const r = nodeRadius(d); return Math.max(r, Math.min(width  - r, d.x)); })
        .attr("cy", d => { const r = nodeRadius(d); return Math.max(r, Math.min(height - r, d.y)); });
    });

    // Expose handles for dimming from filter.js
    window._networkSvgNodes = node;
    window._networkSvgLinks = link;
  }

})();
